const booksData = [



    { title: `JavaScript and JQuery: Interactive Front-End Web Development 1st Edition`, description: `This book was written for anyone who wants to use JavaScript to make their websites a little more interesting, engaging, interactive, or usable. In particular, it is aimed at people who do not have a degree in computer science (well, not yet anyway).

    Programming books can be intimidating, so we wanted to create a book that taught readers how to use JavaScript in a gentler, more visual way. And importantly, we did not want to assume that the reader had any experience of programming beyond the ability to create a web page in HTML and CSS. (After all, many kinds of people are creating websites these days, and not all of us come from a programming background.)`,image:`https://images-na.ssl-images-amazon.com/images/I/31SRWF+LkKL._SX398_BO1,204,203,200_.jpg`, email: `trad.alhariri@gmail.com` },

    { title: `Murach's Java Programming (5th Edition) 5th Edition
    `, description: `This is the 5th edition of Murach's classic Java book that's trained thousands of developers in the last 15 years. Now fully updated to Java 9, this book helps any programmer learn Java faster and better than ever before: [[It's the one Java book that presents object-oriented features like inheritance, interfaces, and polymorphism in a way that's both understandable and useful in the real world. [[It offers new coverage of JavaFX, the date/time API, lambdas, and working with SQLite databases. [[It uses a self-paced approach that works whether you're a beginner or have years of programming experience. [[It's full of practical coding examples that enhance training and that provide starting code for new applications. [[It lets you practice what you've just learned at the end of every chapter, to solidify your skills. [[And it's all done in the distinctive Murach style that has been training professional programmers for more than 43 years.`,image:`https://images-na.ssl-images-amazon.com/images/I/51GcNfql+5L._SX398_BO1,204,203,200_.jpg`,email: `trad.alhariri@gmail.com` },


    { title: `JavaScript and JQuery: Interactive Front-End Web Development 1st Edition`, description: `This book was written for anyone who wants to use JavaScript to make their websites a little more interesting, engaging, interactive, or usable. In particular, it is aimed at people who do not have a degree in computer science (well, not yet anyway).

    Programming books can be intimidating, so we wanted to create a book that taught readers how to use JavaScript in a gentler, more visual way. And importantly, we did not want to assume that the reader had any experience of programming beyond the ability to create a web page in HTML and CSS. (After all, many kinds of people are creating websites these days, and not all of us come from a programming background.)`,image:`https://images-na.ssl-images-amazon.com/images/I/31SRWF+LkKL._SX398_BO1,204,203,200_.jpg`, email: `trad.alhariri@gmail.com` },

    { title: `Murach's Java Programming (5th Edition) 5th Edition
    `, description: `This is the 5th edition of Murach's classic Java book that's trained thousands of developers in the last 15 years. Now fully updated to Java 9, this book helps any programmer learn Java faster and better than ever before: [[It's the one Java book that presents object-oriented features like inheritance, interfaces, and polymorphism in a way that's both understandable and useful in the real world. [[It offers new coverage of JavaFX, the date/time API, lambdas, and working with SQLite databases. [[It uses a self-paced approach that works whether you're a beginner or have years of programming experience. [[It's full of practical coding examples that enhance training and that provide starting code for new applications. [[It lets you practice what you've just learned at the end of every chapter, to solidify your skills. [[And it's all done in the distinctive Murach style that has been training professional programmers for more than 43 years.`,image:`https://images-na.ssl-images-amazon.com/images/I/51GcNfql+5L._SX398_BO1,204,203,200_.jpg`,email: `trad.alhariri@gmail.com` },


    { title: `JavaScript and JQuery: Interactive Front-End Web Development 1st Edition`, description: `This book was written for anyone who wants to use JavaScript to make their websites a little more interesting, engaging, interactive, or usable. In particular, it is aimed at people who do not have a degree in computer science (well, not yet anyway).

    Programming books can be intimidating, so we wanted to create a book that taught readers how to use JavaScript in a gentler, more visual way. And importantly, we did not want to assume that the reader had any experience of programming beyond the ability to create a web page in HTML and CSS. (After all, many kinds of people are creating websites these days, and not all of us come from a programming background.)`,image:`https://images-na.ssl-images-amazon.com/images/I/31SRWF+LkKL._SX398_BO1,204,203,200_.jpg`, email: `trad.alhariri@gmail.com` },

    { title: `Murach's Java Programming (5th Edition) 5th Edition
    `, description: `This is the 5th edition of Murach's classic Java book that's trained thousands of developers in the last 15 years. Now fully updated to Java 9, this book helps any programmer learn Java faster and better than ever before: [[It's the one Java book that presents object-oriented features like inheritance, interfaces, and polymorphism in a way that's both understandable and useful in the real world. [[It offers new coverage of JavaFX, the date/time API, lambdas, and working with SQLite databases. [[It uses a self-paced approach that works whether you're a beginner or have years of programming experience. [[It's full of practical coding examples that enhance training and that provide starting code for new applications. [[It lets you practice what you've just learned at the end of every chapter, to solidify your skills. [[And it's all done in the distinctive Murach style that has been training professional programmers for more than 43 years.`,image:`https://images-na.ssl-images-amazon.com/images/I/51GcNfql+5L._SX398_BO1,204,203,200_.jpg`,email: `trad.alhariri@gmail.com` },

    { title: `JavaScript and JQuery: Interactive Front-End Web Development 1st Edition`, description: `This book was written for anyone who wants to use JavaScript to make their websites a little more interesting, engaging, interactive, or usable. In particular, it is aimed at people who do not have a degree in computer science (well, not yet anyway).

    Programming books can be intimidating, so we wanted to create a book that taught readers how to use JavaScript in a gentler, more visual way. And importantly, we did not want to assume that the reader had any experience of programming beyond the ability to create a web page in HTML and CSS. (After all, many kinds of people are creating websites these days, and not all of us come from a programming background.)`,image:`https://images-na.ssl-images-amazon.com/images/I/31SRWF+LkKL._SX398_BO1,204,203,200_.jpg`, email: `trad.alhariri@gmail.com` },

    { title: `Murach's Java Programming (5th Edition) 5th Edition
    `, description: `This is the 5th edition of Murach's classic Java book that's trained thousands of developers in the last 15 years. Now fully updated to Java 9, this book helps any programmer learn Java faster and better than ever before: [[It's the one Java book that presents object-oriented features like inheritance, interfaces, and polymorphism in a way that's both understandable and useful in the real world. [[It offers new coverage of JavaFX, the date/time API, lambdas, and working with SQLite databases. [[It uses a self-paced approach that works whether you're a beginner or have years of programming experience. [[It's full of practical coding examples that enhance training and that provide starting code for new applications. [[It lets you practice what you've just learned at the end of every chapter, to solidify your skills. [[And it's all done in the distinctive Murach style that has been training professional programmers for more than 43 years.`,image:`https://images-na.ssl-images-amazon.com/images/I/51GcNfql+5L._SX398_BO1,204,203,200_.jpg`,email: `trad.alhariri@gmail.com` }

];

module.exports = booksData;